#!/usr/bin/env bash
# 01_setup.sh — build fuzzer, start DVWS-Node, fetch spec.
#
# DVWS-Node uses docker-compose from the upstream repo.
# Clone it first:
#   git clone https://github.com/snoopysecurity/dvws-node.git /opt/dvws-node
#   cd /opt/dvws-node && docker-compose up -d
set -euo pipefail
cd "$(dirname "$0")/.."
source ./config.env

BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
step() { echo -e "\n${BLUE}>>>${NC} $*"; }
ok()   { echo -e "${GREEN}[OK]${NC} $*"; }
warn() { echo -e "${YELLOW}WARN${NC} $*"; }

# 1. Build fuzzer
step "Building shelob-ng..."
(cd ../.. && go build -o shelob-ng . && ok "shelob-ng built")

# 2. Check DVWS is running
step "Checking DVWS-Node at ${DVWS_URL} ..."
if ! curl -s --connect-timeout 5 "${DVWS_URL}/" &>/dev/null; then
    echo "ERROR: DVWS-Node is not running at ${DVWS_URL}"
    echo ""
    echo "Start DVWS-Node first:"
    echo "  git clone https://github.com/snoopysecurity/dvws-node.git /opt/dvws-node"
    echo "  cd /opt/dvws-node && docker-compose up -d"
    echo "  # Add to /etc/hosts: 127.0.0.1 dvws.local"
    exit 1
fi
ok "DVWS-Node responding at ${DVWS_URL}"

# 3. Fetch the OpenAPI spec (auto-generated by swagger-generator.js)
step "Fetching OpenAPI spec from ${DVWS_URL}/api-docs ..."
HTTP=$(curl -s -o "${SPEC_FILE}" -w "%{http_code}" "${DVWS_URL}/api-docs")
if [ "$HTTP" = "200" ] && [ -s "${SPEC_FILE}" ]; then
    PATHS=$(python3 -c "import json; d=json.load(open('${SPEC_FILE}')); print(len(d.get('paths',{})))" 2>/dev/null || echo "?")
    ok "Spec saved: ${SPEC_FILE} (${PATHS} paths)"
else
    warn "Could not fetch spec from /api-docs (HTTP $HTTP)"
    echo "  Try fetching from the container directly:"
    echo "    docker exec \$(docker ps -qf name=dvws) cat /app/swagger-output.json > ${SPEC_FILE}"
fi

mkdir -p "${CORPUS_DIR}" "${RESULTS_BASE}"

echo ""
echo -e "${GREEN}=== Setup complete ===${NC}"
echo "  DVWS-Node: ${DVWS_URL}"
echo "  Spec:      ${SPEC_FILE}"
echo ""
echo "  NOTE: Add '127.0.0.1 dvws.local' to /etc/hosts if using hostname-based routing"
